pipeline:
  jekyll-build:
    image: jekyll/jekyll:4.2.2
    commands:
      - touch Gemfile.lock
      - chmod a+w Gemfile.lock
      - chown -R jekyll:jekyll /drone
      - gem update --system
      - gem install bundler
      - bundle install
      - bundle exec jekyll build

  deploy:
    image: drillster/drone-rsync
    source: _site/*
    target: ~/docs.hmcl.net
    recursive: true
    delete: true
    when:
      branch: [master]
      event: [push]
